const colors = require('tailwindcss/colors');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,njk,md,svg,js}'],
  safelist: [
    'w-4',
    'h-4',
    'w-5',
    'h-5',
    'mt-8',
    'rounded',
    'rounded-lg',
    'text-3xl',
    'sm:text-4xl',
    'font-extrabold',
    'text-slate-900',
    'tracking-tight',
    'dark:text-slate-200',
    'group',
    'flex',
    'whitespace-pre-wrap',
    '-ml-4',
    'pl-4',
    'absolute',
    '-ml-7',
    'flex',
    'items-center',
    'opacity-0',
    'border-0',
    'group-hover:opacity-100',
    'text-blue-400',
    'hover:text-blue-800',
    'transition-colors',
    'no-underline',
    'bg-slate-200',
    'py-1',
    '-my-1',
    'border-b',
    'hover:text-slate-900',
    'dark:hover:text-slate-400',
    'text-sky-500',
    'hover:text-sky-600',
    'overflow-hidden',
    'relative',
    'w-full',
    'rounded-lg',
    'border',
    'p-4',
    '[&>svg]:absolute',
    '[&>svg]:text-foreground',
    '[&>svg]:left-4',
    '[&>svg]:top-4',
    '[&>svg+div]:translate-y-[-3px]',
    '[&:has(svg)]:pl-11',
    'bg-background',
    'text-foreground',
    'mb-1',
    'font-medium',
    'leading-none',
    'tracking-tight',
    'text-sm',
    '[&amp;_p]:leading-relaxed',
    'mt-0',
    'bg-slate-900/80',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        slate: colors.slate,
        sky: colors.sky,
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animated'),
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
  ],
};
