name: 🔦 Lighthouse
on: [push]
jobs:
  lhci:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: 🧰 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.4

    - name: 📥 Download deps
<<<<<<< HEAD
      uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb
      with:
        useLockFile: false
=======
      run: pnpm install --frozen-lockfile
>>>>>>> 8af99b8 (chore: migrate to pnpm)

    - name: 🏗️ Build
      run: pnpm run build:ci

    - name: 🔦 Run Lighthouse
      run: |
        pnpm dlx @lhci/cli@0.9.x lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}