name: 🔦 Lighthouse
on: [push]
jobs:
  lhci:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: ⎔ Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: 🧰 Enable pnpm
      run: corepack enable

    - name: 📥 Download deps
      run: pnpm install --frozen-lockfile

    - name: 🏗️ Build
      run: pnpm run build:ci

    - name: 🔦 Run Lighthouse
      run: |
        pnpm dlx @lhci/cli@0.9.x lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}