name: 🔗 Linkcheck
on: [push]
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: 🧰 Enable pnpm
      run: corepack enable

    - name: 📥 Download deps
<<<<<<< HEAD
      uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb
      with:
        useLockFile: false
=======
      run: pnpm install --frozen-lockfile
>>>>>>> 8af99b8 (chore: migrate to pnpm)

    - name: 🏗️ Build
      run: pnpm run build:ci

    - name: 🔗 Linkcheck
      uses: untitaker/hyperlink@a3c5f96830515ee0621f21c7b7579f20b9faddcc
      with:
        args: _site/