name: 🔗 Linkcheck
on: [push]
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v5

    - name: ⎔ Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: 🧰 Enable pnpm
      run: corepack enable

    - name: 📥 Download deps
      run: pnpm install --frozen-lockfile

    - name: 🏗️ Build
      run: pnpm run build:ci

    - name: 🔗 Linkcheck
      uses: untitaker/hyperlink@e66bb17cc9ae341677431edec3b893a0aa6ac747
      with:
        args: _site/